---
name: Automated review
on:  # yamllint disable-line rule:truthy
  pull_request:
    types:
    - opened
    - ready_for_review
    - reopened
    - synchronize

permissions: write-all

jobs:
  automated_review:
    name: Generate automated review
    runs-on: ubuntu-latest
    if: ${{ !github.event.pull_request.draft }}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: ros-infrastructure/rosdistro-reviewer@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
